import { readFile } from "node:fs/promises";

import {
  renderDeliveryMessage,
  transportDeliveryContext,
} from "@agent-relay/core";
import type { AgentAttentionEventV1 } from "@agent-relay/protocol";
import { makeProjectRef } from "@agent-relay/protocol";
import { WebhookDeliveryEnvelopeV1Schema } from "@agent-relay/webhook-transport";
import { describe, expect, it } from "vitest";

const occurredAt = "2026-07-28T14:00:00.000Z";
const event: AgentAttentionEventV1 = {
  schema: "agent-attention.v1",
  eventId: "event_fixture_webhook_12345678",
  occurredAt,
  sequence: 1,
  machineId: "machine_fixture_webhook_12345678",
  bridgeSessionId: "bridge_fixture_webhook_12345678",
  harness: "codex",
  surface: "cli",
  harnessVersion: "codex-cli 0.145.0",
  sessionId: "session_fixture_webhook_12345678",
  project: {
    ...makeProjectRef("/synthetic/agent-relay"),
    branch: "main",
  },
  type: "session.ended",
  summary: "Synthetic fixture notification",
  capabilities: {
    inlineContinue: true,
    lateResume: true,
    activeSteer: false,
    permissionDecision: false,
  },
};

describe("public webhook fixture", () => {
  it("is generated by the current presentation and delivery-context boundary", async () => {
    const fixture = WebhookDeliveryEnvelopeV1Schema.parse(
      JSON.parse(
        await readFile(
          new URL(
            "../../../packages/webhook-transport/fixtures/webhook/delivery-v1.json",
            import.meta.url,
          ),
          "utf8",
        ),
      ),
    );
    const context = transportDeliveryContext(event);

    expect(fixture).toEqual({
      schema: "agent-relay-webhook.v1",
      deliveryId: context.idempotencyKey,
      deliveryMode: context.deliveryMode,
      message: renderDeliveryMessage(event, { now: new Date(occurredAt) }),
      source: context.source,
    });
  });
});
